#!/bin/bash 
src="."
dst="./build"

echo From $src
echo To   $dst

cp -R $src/spotify_daemon/src/jukebox  $dst/

cp -R $src/spotify_daemon/src/populate_pldb  $dst/


cp $src/motion_kitty/kitty_controller  $dst/
cp $src/motion_kitty/usb_kittyd $dst/ 

cp -R $src/web/examplesite $dst/




